apiVersion: apps/v1 # this line specifies the API version
kind: Deployment # this line specifies the kind of resource
metadata:
  name: app-one
spec:
  replicas: 1
  selector:
    matchLabels: # this line specifies the labels to match
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: app-one
        image: hashicorp/http-echo
        args: ["-text=Hello from App One"]
        ports: [{ containerPort: 5678 }]
---
apiVersion: v1 # this line specifies the API version
kind: Service # this line specifies the kind of resource
metadata:
  name: app-one-svc
spec:
  selector:
    app: app-one
  ports: [{ port: 80, targetPort: 5678 }]
---
apiVersion: apps/v1 # this line specifies the API version
kind: Deployment # this line specifies the kind of resource
metadata:
  name: app-two
spec:
  replicas: 3
  selector:
    matchLabels: # this line specifies the labels to match
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: app-two
        image: hashicorp/http-echo
        args: ["-text=Hello from App Two"]
        ports: [{ containerPort: 5678 }]
---
apiVersion: v1 # this line specifies the API version
kind: Service # this line specifies the kind of resource
metadata:
  name: app-two-svc
spec:
  selector:
    app: app-two
  ports: [{ port: 80, targetPort: 5678 }]
---
apiVersion: apps/v1 # this line specifies the API version
kind: Deployment # this line specifies the kind of resource
metadata:
  name: app-three
spec:
  replicas: 1
  selector:
    matchLabels: # this line specifies the labels to match
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
      - name: app-three
        image: hashicorp/http-echo
        args: ["-text=Hello from App Three"]
        ports: [{ containerPort: 5678 }]
---
apiVersion: v1 # this line specifies the API version
kind: Service # this line specifies the kind of resource
metadata:
  name: app-three-svc
spec:
  selector:
    app: app-three
  ports: [{ port: 80, targetPort: 5678 }]
---
